### ISSUE TITLE
User and Task Modules

### ISSUE THREAD

**Issue by sarah-abu-zeineh** [sarah-abu-zeineh/todo-api#1]
**Description**: Create the user module to handle user registration, authentication, and management.
**Tasks**:

- [x] Generate user module.
- [x] Define user schema (MongoDB).
- [x] Implement user service for user-related business logic.
- [x] Create user controller for API endpoints.
- [x] Create task controller for API endpoints.
