### ISSUE TITLE
Mail Service

### ISSUE THREAD

**Issue by sarah-abu-zeineh** [sarah-abu-zeineh/todo-api#3]
**Description**: Set up a mail service for account recovery and verification.
**Tasks**:

- [x] Install and configure mailer module.
- [x] Create mail service to send emails.
- [x] Define email templates for account recovery and verification.
- [x] Integrate mail service into auth service for sending verification and recovery emails.
